### ISSUE TITLE
S3 bucket docker container

### ISSUE THREAD

**Issue by AmitGit217** [Mathmate-il/mathmate-server#48]
**Is your feature request related to a problem? Please describe.**
We will need to save users' images, we can't just save blobs in the DB columns, and we must use a saas for it.

**Describe the solution you'd like**
We can emulate the process for development needs with a docker image called S3 ninja that serves the same way.

**Describe alternatives you've considered**
Trying to control the flow manually?

**Comment by Flexusaurs** [comment]
if it's a must to go a SAAS solution, i can try to set up one on linode or GCP, I just need to do some calculations regarding which is is pricier and if it's payment by usage or by uptime. eitherway, by thursday I'll set up a bucket

**Comment by AmitGit217** [comment]
I will try today or tomorrow to sit on this
