### ISSUE TITLE
Swagger oAuth2.0 support

### ISSUE THREAD

**Issue by AmitGit217** [Mathmate-il/Mathmate-server#50]
**Is your feature request related to a problem? Please describe.**
We want to test our server authentication service without the need to open the front end and use the swagger UI.

**Describe the solution you'd like**
Probably creating a dummy google user just for tests and getting his credentials and saving it for the auth.

**Additional context**
Are the credentials always the same?

**Comment by ShohamD1121** [comment]
I've tried following this article : 

https://medium.com/tech-takeaways/how-to-perform-oauth-2-0-authorization-with-postman-2bfbde062959

I'd suggest you try it with your user credentials to get a hang of what's going on, for some reason it didn't work for me.

I think creating a general user for testing isn't a bad idea at all.

let me know what your thoughts on this article.

**Comment by AmitGit217** [comment]
Thank you I will try that
